### ISSUE TITLE
Getting wrong MimeType

### ISSUE THREAD

**Issue by Cyberavater** [DATL4G/MimeMagic-Android#1]
It's giving me the wrong MimeType for this image file

![img_12_1675161077125](https://user-images.githubusercontent.com/32187927/219623160-300e5628-3c2b-4da2-9fda-ca9e87823763.jpg)

**Comment by DatL4g** [comment]
Which MIME type is it reporting? And which method did you use?

**Comment by Cyberavater** [comment]
mimeType: audio/x-wav

`fromFile(path.toFile()).mimeType`

**Comment by Cyberavater** [comment]
You can also download this image to check, apparently the github doesn't compress the image (verified by hash).

**Comment by DatL4g** [comment]
The image is a WebP which is a container format based on RIFF. This format is not fully supported by all devices and not even across all browsers, so they may detect different types.
Possible output types for this image are: `audio/qcelp`, `audio/x-wav`, `image/webp`, `video/x-msvideo`

Since this library is just a wrapper of system provided functions and no self implementation by checking bytes, there is nothing I can do about it.
Every device could report different results for this, best you could do is a check if it's an image by using the `fromUri` method and then check by the `fromFile` method and if it's any of the above mentioned you know it's a WebP.
This however can be painful performance-wise and not very practical when you have a more generic use-case, like selecting any file and it could be any mime-type.
In this case I suggest you to use a library that's checking the type by bytes
